joint_1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_1
    joint_speed: 0.5
    motor:
        id: 0
        init: 1980
        min: 1980
        max: 17140


joint_2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_2
    joint_speed: 0.5
    motor:
        id: 1
        init: 1940
        min: 1940
        max: 12000


joint_3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_3
    joint_speed: 0.5
    motor:
        id: 2
        init: 1685
        min: 1680
        max: 17500


joint_4:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_4
    joint_speed: 0.5
    motor:
        id: 3
        init: 1150
        min: 1150
        max: 9770


joint_5:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_5
    joint_speed: 0.5
    motor:
        id: 4
        init: 1030
        min: 1030
        max: 5725


joint_6:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_6
    joint_speed: 0.5
    motor:
        id: 5
        init: 995
        min: 0
        max: 4096





